services:
  localstack:
    image: localstack/localstack:latest
    container_name: dynamodb_wrapper_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DYNAMODB_ERROR_PROBABILITY=0.0
      - DYNAMODB_SHARE_DB=1
      - PERSISTENCE=0
      - LS_LOG=trace
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s